### ISSUE TITLE
Search nearest neighbor by range?

### ISSUE THREAD

**Issue by shlomiw** [splitice/QuadTrees#2]
Hi,

I'm playing with you very nice lib for gaming.
It's very good for maintaining the units (i.e. `Move` method) and collision detection.

I have also requirement to find the nearest neighbor by range (i.e. find unit to attack).
But, the QuadTree doesn't expose public methods to traverse the nodes. I was hoping to try to do a kind of 'circular' traversal of the nodes around my unit node and try to find the nearest neighbor. Should be faster then searching the full bounding box of the entire possible range around the unit (i.e. consider units with very long range).

What do you think?

**Comment by splitice** [comment]
Possilbly, but it's not that simple. Feel free to PR and I'll review.
