### ISSUE TITLE
MaxObjectsPerNode should be a property when creating QuadTree

### ISSUE THREAD

**Issue by shlomiw** [splitice/QuadTrees#3]
MaxObjectsPerNode is now a const equals to 10.
I'd like to be able to set it when creating the QuadTree.
Thanks

**Comment by splitice** [comment]
Why? QuadTree's will split automatically.

That number was chosen based on extensive profiling. And should be fine for all use cases.

If it was to be made non-const profiling would be required illustrating no negative effect.

**Comment by shlomiw** [comment]
In my case I'd rather test with smaller number.
It's a small board area with sparse units most of the time.

**Comment by splitice** [comment]
Feel free to fork.

**Comment by shlomiw** [comment]
Ok, thanks :)
