### ISSUE TITLE
Assertion failed trying to update the rect/bounds.

### ISSUE THREAD

**Issue by ItsEddie** [splitice/QuadTrees#4]
I'm trying to update the bounds of the objects in the quadtree (since I'm creating a game this has to be done every update tick), but to no avail. Got an 'assertion failed' exception at:

`                     
   Debug.Assert(beforeCount + child._objectCount == Count); 
`
in QuadTreeNodeCommon.cs. 

`

        public virtual void Update(GameTime gametime)
        {
            _Bounds.X = (int)Position.X;
            _Bounds.Y = (int)Position.Y;
            _Bounds.Width = (int)Shape.AABB.Width;
            _Bounds.Height = (int)Shape.AABB.Height;

            // -- throws
            Tree.Remove(this);
            Tree.Add(this);

            // -- throws
            Tree.Move(this);
        }

`
`

    public class QuadObject : IRectQuadStorable

        private Rectangle _Bounds = Rectangle.Empty;
        /// <summary>
        /// The bounds of the shape.
        /// </summary>
        public Rectangle Bounds
        {
            get
            {
                return _Bounds;
            }
        }

        /// <summary>
        /// Creates a new quad object.
        /// </summary>
        /// <param name="tree">The quad tree the object will be in.</param>
        public QuadObject(QuadTreeRect<QuadObject> tree)
        {
            Tree = tree;
            Tree.Add(this);
        }

`

Bounds is the 'Rect' from the Interface, I just adjusted the name in the source code to fit my original class.

**Comment by splitice** [comment]
Hi,

Sounds to me like Quad Tree corruption such as the same object inserted multiple times etc. 

Unfortunately I am not currently using this library in any active project as such it is not under development outside of review of external PRs.
