### ISSUE TITLE
included rectangle result error

### ISSUE THREAD

**Issue by markus27183** [splitice/QuadTrees#6]
With the code: 

QuadTreeRectF<QTreeObject> qtree = new QuadTreeRectF<QTreeObject>();
qtree.Add( new QTreeObject( new RectangleF( 1, 1, 20, 20 ) ) );
var result = qtree.GetObjects( new RectangleF( 0.9f, 0.9f, 0.91f, 0.91f ) );

The result contains the added rectangle, although it shouldn't

**Comment by splitice** [comment]
Incorrect, you should expect one result. See the test https://github.com/splitice/QuadTrees/blob/master/QuadTrees.Tests/TestRectangle.cs#L35

Default configuration is for intersection. You may want to introduce a class for containing if that matches your use cases.

**Comment by markus27183** [comment]
In my example, the rectangle 
  RectangleF( 1, 1, 20, 20 ) ) );
neither contains nor intersects the rectangle
  RectangleF( 0.9f, 0.9f, 0.91f, 0.91f );
?

**Comment by splitice** [comment]
0.9+0.9 =1.8. 1 < 1.8 < 21  it intersects.

**Comment by markus27183** [comment]
My mistake, I thought the Rectangle params were top left and bottom right coords.   
Good code :)
